# Generated by Django 5.1.3 on 2024-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_perfium_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogImg',
            field=models.ImageField(default='photos/N2-2.png', upload_to='photos'),
        ),
    ]
