# Generated by Django 5.1.3 on 2024-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_gendar_alter_perfium_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfium',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('uni', 'Unisex')], default='50ml', max_length=20),
        ),
        migrations.DeleteModel(
            name='Gendar',
        ),
    ]
