# Generated by Django 5.1.3 on 2024-11-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_gendar_alter_perfium_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('sizePrice', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
