# Generated by Django 5.1.3 on 2024-11-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_perfumsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfium',
            name='smallText',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
