# Generated by Django 5.1.3 on 2024-11-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_mysetting_fax_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysetting',
            name='owner_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
