# Generated by Django 5.1.3 on 2024-11-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_mysetting_owner_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfium',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='perfium',
            name='low_price',
        ),
    ]
